nelmio_api_doc:
    documentation:
        info:
            title: Stripe Mirakl Connector
            description: >
                This connector allows marketplaces powered by Mirakl to onboard sellers on Stripe and pay them out automatically.
            version: 3.0.1
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Token configured by the operator during the installation'
                name: X-AUTH-TOKEN
                in: header

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc)(?!/contexts)(?!/{index}) # Accepts routes under /api except /api/doc, /api/context, /api/{index}
